登張さんのインタビュー記事をコミット
nishi-owls/nishi-owls pull request #133
Opened 2024-09-21 16:16 UTC by numa72

日を跨いじゃってすいません。
登張さんのインタビュー記事です。

2024-09-22 04:38 UTC, tossy310 requested changes
お忙しい中ありがとうございます！

2024-09-22 04:38 UTC, tossy310 commented on _posts/2024/2024-09-22-obog06-tobari.md
> +image: 2022/ohashi/main.jpg
```suggestion
image: 2024/tobari/main.jpg
```

あと、これは好みの問題かもですが、画像自体についても、いくつか思ったことです：
* 他のmain画像と比べて、顔が少し小さい気がしました。
* 右上の画像は、現役時の写真のほうが良いかなと思うのですが、どうでしょうか。（今までのインタビュー記事は必ず現役時代のものを入れていました。）
* 右下の画像は、登張さんにもっとズームインしても良いのでは、と思いました。今のままだと、なんか人がいっぱいいる、くらいしか分からないので。。。

いかがでしょうか。

2024-09-22 04:38 UTC, tossy310 commented on _posts/2024/2024-09-22-obog06-tobari.md
> +<strong>登張 信實（とばり　のぶみ）</strong>
```suggestion
<strong>登張 信實（とばり のぶみ）</strong>
```

特別な理由が無い限り、半角スペースをつかいたいです。

2024-09-22 04:38 UTC, tossy310 commented on _posts/2024/2024-09-22-obog06-tobari.md
> +1998年春から2005年春までOWLS監督。2001年春大会ではチームを都大会第4位、関東大会第3位へと導いた。2007年４月から2009年3月まで関東学生アメリカンフットボール連盟理事長。
```suggestion
1998年春から2005年春までOWLS監督。2001年春大会ではチームを都大会第4位、関東大会第3位へと導いた。2007年4月から2009年3月まで関東学生アメリカンフットボール連盟理事長。
```

同様に半角英数字をつかいたいです。他にも結構いろんな箇所に全角英数字・スペースが混ざっているので、適当なコマンドとかで全角を半角に一括置換していただけると。

2024-09-22 04:38 UTC, tossy310 commented on _posts/2024/2024-09-22-obog06-tobari.md
> +<img src="/assets/images/topics/2024/tobari/17th.jpg" alt="OWLS17期"><br/>
こちらは53期の写真ではないでしょうか。監督されていた時代の写真です。（ちなみに右端の人が登張さんなのか否かはわかりません。）

53期の写真も監督時のチームの写真として使いたいですが、それに加えて現役時代の写真も入れたいですね。17期の写真は記念誌からのスキャンしか無いので、それをいい感じに使って頂けると。

2024-09-22 04:38 UTC, tossy310 commented on _posts/2024/2024-09-22-obog06-tobari.md
> +social_description: 東京大学WARRIORSやOWLSでの監督や関東学生アメリカンフットボール連盟理事長を歴任し、現在はベンチサイドでの解説が好評を博している登張 信實氏（17期）に話を伺った。常に“自らにできることは何か”を考え、実践してきた登張氏の原点を紐解いていく。
```suggestion
social_description: 東京大学WARRIORSや西高OWLSでの監督や関東学生アメリカンフットボール連盟理事長を歴任し、現在はベンチサイドでの解説が好評を博している登張 信實氏（17期）に話を伺った。常に“自らにできることは何か”を考え、実践してきた登張氏の原点を紐解いていく。
```

並列されるものは同じ粒度のものを並べたい気持ちです。本文も同様です

2024-09-22 04:38 UTC, tossy310 commented on _posts/2024/2024-09-22-obog06-tobari.md
> +<img src="/assets/images/topics/2024/tobari/tobari3.jpg" alt="ユーモアを交えて試合を解説する登張氏の写真"><br/>
assets_data のほうの写真も含め、保護者の顔にはモザイク入れてほしいです

2024-09-22 04:38 UTC, tossy310 commented on _posts/2024/2024-09-22-obog06-tobari.md
> +「東京大学の監督を6年間やった後、小野さん（註：13期小野 恵稔氏。初代監督）から引き継ぐ形でOWLSの監督になりました。頼まれたら断れないタイプなので（笑）。当時は学生コーチが１人で全部をやっていました。しばらくは様子を見ていましたが、さすがに難しいのではないかと思いました。“誰か仲間を連れてきなよ”と言うと、しばらくして加藤君（註：49期加藤　喜秋氏）、西村君（註：49期西村　啓太氏）たちが
* 小野さんは過去のインタビュー記事、平岡さんは監督コメントにリンクにするという話だった記憶があります。
* 名字と名前の間は半角スペースに統一したいです。

2024-09-22 04:38 UTC, tossy310 commented on _posts/2024/2024-09-22-obog06-tobari.md
> +※アメリカンフットボールでは、ボールキャリアが倒れる位置によって、時計が止まるか否かが変わる。<br/>
footnote は CSS でインデントを入れているので、ここで空白を入れると2重にスペースが見えて不自然になると思います。

https://github.com/nishi-owls/nishi-owls/blob/eaacca712063a83395973f33ca7f4b23afb46319/_sass/topics.scss#L102-L105

行頭の空白は不要かと思います。

2024-09-22 04:38 UTC, tossy310 commented on _posts/2024/2024-09-22-obog06-tobari.md
> +<img src="/assets/images/topics/2024/tobari/tobari1.jpg" alt="登張氏写真"><br/>
optional なのですが、写真の上部の赤い場所の文字消せないですかね.... ちょっとダサい気がしました。自分がやるのでもいいです。

2024-09-22 04:38 UTC, tossy310 commented on _posts/2024/2024-09-22-obog06-tobari.md
> +「監督を退任した後も、OWLSの試合は必ず見に行っています。ある時、ベンチが“中で倒せ”や “外に出せ”と言っているのを聞いた保護者が、どういう意味なのかと不思議がっていました。経験者であればタイムマネジメントはフットボールで一番大事な要素なのでその意味がわかりますが（※）、保護者からしたらそこまでは当然分からないわけです。それであれば、保護者がもっと楽しんで観戦できるようにと、メガホンを使って
```suggestion
「監督を退任した後も、OWLSの試合は必ず見に行っています。ある時、ベンチが“中で倒せ”や “外に出せ”と言っているのを聞いた保護者が、どういう意味なのかと不思議がっていました。経験者であればタイムマネジメントはフットボールで一番大事な要素なのでその意味がわかりますが<sup>（※）</sup>、保護者からしたらそこまでは当然分からないわけです。それであれば、保護者がもっと楽しんで観戦できるようにと、メガホンを使って解説するようになりました。」
```

今まで上付きにしていたので、統一したいです。

2024-09-22 04:44 UTC, tossy310 commented on _posts/2024/2024-09-22-obog06-tobari.md
> +image: 2022/ohashi/main.jpg
右下の画像についてもう一回考えると、これをアップしても微妙なので、 `tobari3.jpg` のほうを元に登張さんにアップして切り取ったほうが良いのかも、と思い始めました。

2024-09-26 13:25 UTC, numa72 commented on _posts/2024/2024-09-22-obog06-tobari.md
> +「監督を退任した後も、OWLSの試合は必ず見に行っています。ある時、ベンチが“中で倒せ”や “外に出せ”と言っているのを聞いた保護者が、どういう意味なのかと不思議がっていました。経験者であればタイムマネジメントはフットボールで一番大事な要素なのでその意味がわかりますが（※）、保護者からしたらそこまでは当然分からないわけです。それであれば、保護者がもっと楽しんで観戦できるようにと、メガホンを使って
遅くなっててごめん。今週末までには対応するのでもう少し待って

2024-09-29 02:28 UTC, numa72 commented on _posts/2024/2024-09-22-obog06-tobari.md
> +image: 2022/ohashi/main.jpg
指摘にある通り、53期の写真を現役時代の写真と勘違いしてました。
右上を選手時代、右下をtobari4(元tobari3、後の指摘で画像を追加したので番号が修正)の顔のアップにしてサムネの写真を直しました

2024-09-29 02:30 UTC, numa72 commented on _posts/2024/2024-09-22-obog06-tobari.md
> +1998年春から2005年春までOWLS監督。2001年春大会ではチームを都大会第4位、関東大会第3位へと導いた。2007年４月から2009年3月まで関東学生アメリカンフットボール連盟理事長。
正規表現で検索して一通り全角を直しました。

2024-09-29 02:32 UTC, numa72 commented on _posts/2024/2024-09-22-obog06-tobari.md
> +<img src="/assets/images/topics/2024/tobari/17th.jpg" alt="OWLS17期"><br/>
すいません。勘違いでしたので直しました。
冊子から取った写真に入れ替えました。
元の写真もtobari2として監督時代の写真として追加しました。
それに伴い、旧tobari2→tobari3, 旧tobari3→tobari4に直しました。

2024-09-29 02:39 UTC, numa72 commented on _posts/2024/2024-09-22-obog06-tobari.md
> +social_description: 東京大学WARRIORSやOWLSでの監督や関東学生アメリカンフットボール連盟理事長を歴任し、現在はベンチサイドでの解説が好評を博している登張 信實氏（17期）に話を伺った。常に“自らにできることは何か”を考え、実践してきた登張氏の原点を紐解いていく。
本文共々直しました。

2024-09-29 02:41 UTC, numa72 commented on _posts/2024/2024-09-22-obog06-tobari.md
> +※アメリカンフットボールでは、ボールキャリアが倒れる位置によって、時計が止まるか否かが変わる。<br/>
なくしました

2024-09-29 02:43 UTC, numa72 commented on _posts/2024/2024-09-22-obog06-tobari.md
> +「監督を退任した後も、OWLSの試合は必ず見に行っています。ある時、ベンチが“中で倒せ”や “外に出せ”と言っているのを聞いた保護者が、どういう意味なのかと不思議がっていました。経験者であればタイムマネジメントはフットボールで一番大事な要素なのでその意味がわかりますが（※）、保護者からしたらそこまでは当然分からないわけです。それであれば、保護者がもっと楽しんで観戦できるようにと、メガホンを使って
上付きにしました

2024-09-29 02:46 UTC, numa72 commented on _posts/2024/2024-09-22-obog06-tobari.md
> +<img src="/assets/images/topics/2024/tobari/tobari1.jpg" alt="登張氏写真"><br/>
上の指摘のトリミングの過程で消えました。

2024-09-29 03:13 UTC, numa72 commented on _posts/2024/2024-09-22-obog06-tobari.md
> +<img src="/assets/images/topics/2024/tobari/tobari3.jpg" alt="ユーモアを交えて試合を解説する登張氏の写真"><br/>
モザイクかけました

2024-09-29 03:23 UTC, numa72 commented on _posts/2024/2024-09-22-obog06-tobari.md
> +「東京大学の監督を6年間やった後、小野さん（註：13期小野 恵稔氏。初代監督）から引き継ぐ形でOWLSの監督になりました。頼まれたら断れないタイプなので（笑）。当時は学生コーチが１人で全部をやっていました。しばらくは様子を見ていましたが、さすがに難しいのではないかと思いました。“誰か仲間を連れてきなよ”と言うと、しばらくして加藤君（註：49期加藤　喜秋氏）、西村君（註：49期西村　啓太氏）たちが
リンク付けました。
全角スペースは上の指摘対応でなくしました

2024-09-29 03:26 UTC, numa72 commented
レビュー指摘一通り修正したので確認お願いします。

2024-09-29 06:55 UTC, tossy310 reviewed
少し小さい指摘をしましたが、全体的に良い感じだと思います！ありがとう御座います！

直したら日付を適当に10月の中旬くらいにしておいて、とりあえずBOD内にシェアして内容確認に進みたいです。

2024-09-29 06:55 UTC, tossy310 commented on _posts/2024/2024-09-22-obog06-tobari.md
> +「東京大学の監督を6年間やった後、<a href="https://www.nishi-owls.com/topics/2021/12-29-obog02-ono.html">小野さん（註：13期小野 恵稔氏。初代監督）</a>から引き継ぐ形でOWLSの監督になりました。頼まれたら断れないタイプなので（笑）。当時は学生コーチが 1人で全部をやっていました。しばらくは様子を見ていましたが、さすがに
```suggestion
「東京大学の監督を6年間やった後、小野さん（[註：13期小野 恵稔氏。初代監督](/topics/2021/12-29-obog02-ono.html)）から引き継ぐ形でOWLSの監督になりました。頼まれたら断れないタイプなので（笑）。当時は学生コーチが 1人で全部をやっていました。しばらくは様子を見ていましたが、さすがに難しいのではないかと思いました。“誰か仲間を連れてきなよ”と言うと、しばらくして加藤君（註：49期加藤 喜秋氏）、西村君（註：49期西村 啓太氏）たちが来てくれ、その後平岡君（[註：47期平岡 成太氏。現監督](/message/coach-ob.html#coach)）も来てくれて、ずいぶんとスタッフは充実しました。」
```

- markdownで簡潔にできるリンクは簡潔にしました。
- リンクにドメイン名を含めるとステージング環境でリンク先が正しくなくなるので、ドメインを外しました
- 平岡監督の苗字と名前の間に半角スペースを入れました
- 原稿とリンク範囲が違う気がするので原稿に合わせました

2024-09-29 06:55 UTC, tossy310 commented on _posts/2024/2024-09-22-obog06-tobari.md
> +<p class='footnote'>
これ、 `{.footnote}` の形で簡単に書けないですかね

参考:
https://github.com/nishi-owls/nishi-owls/blob/9d681a5de0abe3e5b628de97fe56fb0406da7ad9/_posts/2024/2024-08-07-obog05-shojima.md?plain=1#L122

2024-09-29 06:55 UTC, tossy310 commented on _posts/2024/2024-09-22-obog06-tobari.md
> +image: 2022/ohashi/main.jpg
いい感じだと思います、ありがとうございます

2024-10-02 11:44 UTC, numa72 commented on _posts/2024/2024-09-22-obog06-tobari.md
> +「東京大学の監督を6年間やった後、<a href="https://www.nishi-owls.com/topics/2021/12-29-obog02-ono.html">小野さん（註：13期小野 恵稔氏。初代監督）</a>から引き継ぐ形でOWLSの監督になりました。頼まれたら断れないタイプなので（笑）。当時は学生コーチが 1人で全部をやっていました。しばらくは様子を見ていましたが、さすがに
指摘通り直しました

2024-10-02 11:44 UTC, numa72 commented on _posts/2024/2024-09-22-obog06-tobari.md
> +<p class='footnote'>
直しました

2024-10-02 11:48 UTC, numa72 commented
追加指摘直しました。確認お願いします。(Approveにしてもらえたらマージします)

2024-10-02 11:57 UTC, tossy310 commented
LGTM ですが、マージ前に BOD 内で確認などしてから正式に公開したいので、一旦保留にさせてください〜

2024-10-02 12:12 UTC, numa72 commented
BODで共有ってマージ前に共有ってことか！了解です！

2024-10-02 12:41 UTC, tossy310 commented
`netlify` ブランチにこのブランチをマージしました。Netlify cms を使って編集してもらう機能が使えるはず...

2024-10-02 12:51 UTC, tossy310 commented
説明をしておくと、 Netlify のブランチからログインするとウェブ上から編集できて、 https://github.com/nishi-owls/nishi-owls/pull/135 こういうPRが作られるようになっています。PRになるので、いつものフローが走り、編集のプレビューもちゃんと生成されています。

2024-10-12 02:33 UTC, tossy310 commented
@numa72 
校正大体できたようなので、 #135 から差分だけ、こっちに引っ張ってきてもらえますか？

2024-10-12 02:38 UTC, tossy310 commented
（補足しておくと、netlifyブランチはMCS機能用に色々と追加のconfigとかが入っているので、それらは不要で、記事を編集したコミット達だけこのブランチに引っ張ってきたいという感じです。）

2024-10-22 13:09 UTC, numa72 commented
お待たせしました。しました(ファイル名を明日にリネームしてます)

2024-10-23 12:51 UTC, tossy310 approved these changes
ありがとうございます！！！！LGTM

2024-10-24 11:25 UTC, merged