Update links. Close #49
nishi-owls/nishi-owls pull request #51
Opened 2022-07-27 12:28 UTC by tossy310

来年以降もう少し楽になるような仕組みがあると良さそうですが、とりあえず今年はこれで...

2022-07-27 13:32 UTC, numa72 commented
明日レビューするんで少々お待ちを

2022-07-28 12:07 UTC, numa72 requested changes
レビューしました。2か所リンクの更新漏れの指摘があります。

2022-07-28 12:07 UTC, numa72 commented on _data/link.yml
> +        - name: パナソニックインパルス
後、今回の改修範囲じゃないから参照できないのでこっちに書くけど、西高のサイトも[ここ](https://www.metro.ed.jp/nishi-h/)に移転してます。

2022-07-28 13:23 UTC, tossy310 commented
@numa72 直しました！確認ありがとうございます

2022-07-29 13:39 UTC, numa72 approved these changes
修正確認しました。対応ありがとうございます。

2022-07-29 13:47 UTC, merged